# Generated by Django 4.2.14 on 2024-08-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mydata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=25)),
                ("fname", models.CharField(max_length=20)),
                ("lname", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("pass1", models.CharField(max_length=8)),
                ("pass2", models.CharField(max_length=8)),
            ],
        ),
    ]
