# Generated by Django 4.2.14 on 2024-08-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mydata", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="fname",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="lname",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="pass2",
        ),
    ]
